### ISSUE TITLE
Missing header even if present in PATH

### ISSUE THREAD

**Issue by ParanoidNemo** [AOSPA/android_frameworks_av#1]
Hi all,
I've this error when building AOSPA-CAF 6 for huashan
`frameworks/av/media/libstagefright/SurfaceMediaSource.cpp:39:10: fatal error: 'gralloc_priv.h' file not found
# include <gralloc_priv.h>

```
     ^
```

1 error generated.
make: **\* [build/core/binary.mk:706: out/target/product/huashan/obj/SHARED_LIBRARIES/libstagefright_intermediates/SurfaceMediaSource.o] Error 1`

The fact is that I've the file gralloc_priv.h
here: $HOME/incubator/AOSPA-CAF/hardware/libhardware/modules/gralloc/gralloc_priv.h
and here: $HOME/incubator/AOSPA-CAF/hardware/qcom/display-caf/msm8960/libgralloc/gralloc_priv.h

**Comment by GalaticStryder** [comment]
Could you please close this error? It has nothing to do with PA code but your device's hardware code. Also, it has passed a month so either you've fixed or gave up.
